### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
!pip install numpy




[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
# 2D and 3D

b = np.array(
    [
    [1,2,3],
    [1,2,3]
    ]
)

print(a)

[1 2 3]


In [18]:
#3d
# shape = 2,2,2
c = np.array(
    [
        [
            [1,2],
            [2,3]
        ],
        [
            [5,6],
            [7,8]
        ]
    ]
)

a          

array([1, 2, 3])

In [25]:
# dtype

np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [27]:
import numpy as np

a = np.array([-1,2,3], dtype = bool)
a

array([ True,  True,  True])

In [29]:
# np.arange

np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(1,5,2)

array([1, 3])

In [32]:
a.shape

(3,)

In [33]:
b.shape

(2, 3)

In [34]:
c.shape

(2, 2, 2)

In [43]:
# with reshape

np.arange(16).reshape(16,) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
# np.ones and np.zeros

np.ones((3,4))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.ones((3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [48]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
# np.random

np.random.random((3,4))

array([[0.71544961, 0.98750944, 0.80765453, 0.13263521],
       [0.8573646 , 0.13465619, 0.53741954, 0.98325231],
       [0.06528159, 0.93448282, 0.12087272, 0.35122042]])

In [64]:
np.random.randint(1,7,(3,4))

array([[4, 4, 6, 2],
       [2, 1, 5, 5],
       [2, 1, 2, 1]])

In [65]:
# np.linspace

np.linspace(10,20,5) 


array([10. , 12.5, 15. , 17.5, 20. ])

In [66]:
# np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [78]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [79]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [80]:
# shape

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [81]:
# size

a2.size

12

In [82]:
# itemsize

a1.itemsize
a2.itemsize

8

In [85]:
# dtype

a1.dtype
a2.dtype
a3.dtype


dtype('int64')

### Changing Datatype

In [86]:
# astype

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [87]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [89]:
# scalar operations

# arithmetic

a1 = np.arange(16).reshape(4,4)
a2 = np.arange(30,46).reshape(4,4)


In [90]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
a2

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45]])

In [96]:
a1 ** 2 

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [97]:
a2

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45]])

In [99]:
# relational

a2 > 30


array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [100]:
# vector operations
# arithmetic

np.dot(a1,a2)


array([[ 236,  242,  248,  254],
       [ 812,  834,  856,  878],
       [1388, 1426, 1464, 1502],
       [1964, 2018, 2072, 2126]])

### Array Functions

In [101]:
a1 = np.arange(12).reshape(3,4)

In [102]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
np.sum(a1)

np.int64(66)

In [104]:
np.max(a1)

np.int64(11)

In [105]:
np.prod(a1)

np.int64(0)

In [107]:
# max/min/sum/prod
# 0 -> col and 1 -> row

np.prod(a1, axis = 0 )

array([  0,  45, 120, 231])

In [108]:
# mean/median/std/var

np.mean(a1, axis = 1 )

array([1.5, 5.5, 9.5])

In [109]:
# trigonomoetric functions

np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [48]:
# dot product


In [110]:
# log and exponents
a1 = np.arange(16).reshape(4,4)
a2 = np.arange(30,46).reshape(4,4)

In [114]:
np.exp(a1)     

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [115]:
np.exp(a2)

array([[1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16],
       [3.18559318e+16, 8.65934004e+16, 2.35385267e+17, 6.39843494e+17],
       [1.73927494e+18, 4.72783947e+18, 1.28516001e+19, 3.49342711e+19]])

In [119]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)


array([[ 4., 47., 81.],
       [64., 50., 61.]])

### Indexing and Slicing

In [120]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

In [121]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a[0:5:2]

array([0, 2, 4])

In [134]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
b[1]

array([4, 5, 6, 7])

In [130]:
b[2,3]

np.int64(11)

In [131]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [132]:
c.shape

(2, 2, 2)

In [141]:
c[1,1,1]

np.int64(7)

In [142]:
c[0,1,1]

np.int64(3)

In [ ]:
# slicing

In [143]:
#1D   syntax [ start:endpoint:stride(steps) ]

a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
a[:5] = 5

In [149]:
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [150]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
# 3 rows , 3 columns  syntax [ row_slice, column_slice ]
b[1]

array([4, 5, 6, 7])

In [154]:
b[1, : ]

array([4, 5, 6, 7])

In [157]:
b[:,1]

array([1, 5, 9])

In [158]:
b[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [159]:
b[::2, ::2]  

array([[ 0,  2],
       [ 8, 10]])

In [160]:
b[:,-1]

array([ 3,  7, 11])

In [161]:
b[::2, ::2] = 0

In [162]:
b

array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 0,  9,  0, 11]])

In [163]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [164]:
c = np.arange(12).reshape(3,2,2)

In [165]:
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [166]:
# [depth_slice, row_slice, column_slice]

c[0]

array([[0, 1],
       [2, 3]])

In [168]:
c[1,0]

array([4, 5])

In [169]:
c[1,0,1]

np.int64(5)

In [172]:
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [174]:
c[:,0:1,:]

array([[[0, 1]],

       [[4, 5]],

       [[8, 9]]])

In [176]:
c[:,:,0:2]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [177]:
c [ 1:, 0:1, :]

array([[[4, 5]],

       [[8, 9]]])

### Iterating

In [178]:
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [179]:
for i in a:
    print(i)

5
5
5
5
5
5
5
5
5
5


In [180]:
b

array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 0,  9,  0, 11]])

In [182]:
for i in b:
    print(i)

[0 1 0 3]
[4 5 6 7]
[ 0  9  0 11]


In [184]:
for i in c:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]


In [187]:
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
