# Ultimate ML DL BootCamp- NumPy Assignment



#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.show_config())
print(np.__version__)

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35213",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35213",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib directo

c:\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [24]:
x = np.array([100,20,34])
x.size*x.itemsize


24

In [25]:
x.nbytes

24

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [36]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [39]:
y = np.arange(10) == 4
y*1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [40]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [42]:
a = np.arange(10,50)
np.flip(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [43]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [47]:
l =[1,2,0,0,4,0]
[i for i in l if i !=0]

np.nonzero(l)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [60]:
np.random.rand(3,3,3)

array([[[0.09326056, 0.06370997, 0.81007501],
        [0.54453749, 0.68779398, 0.76496844],
        [0.22889406, 0.72199078, 0.65337163]],

       [[0.21762286, 0.0045443 , 0.78327754],
        [0.38614369, 0.92816304, 0.87373035],
        [0.88106176, 0.14502552, 0.73335475]],

       [[0.24756582, 0.77959315, 0.4491494 ],
        [0.77221649, 0.71981469, 0.34048934],
        [0.23666987, 0.68244974, 0.25319361]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
arr = np.random.randn(10,10)
arr.min(), arr.max()

(np.float64(-2.079557370826614), np.float64(1.5791072965704398))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [65]:
np.random.random(30).mean()

np.float64(0.5171513015600889)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [81]:
for i in range(1,6):
    for j in range(1, 6):
        print(1 if i==1 or j==1 or i==5 or j==5 else 0, end=' ')
    print()

1 1 1 1 1 
1 0 0 0 1 
1 0 0 0 1 
1 0 0 0 1 
1 1 1 1 1 


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

np.pad(arr,pad_width=1, mode='constant', constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [7]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] =1
arr[::2, 1::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [49]:
base = np.array([[0, 1],
                 [1, 0]])

np.tile(base, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [56]:

Z = np.random.random((5,5))

(Z - Z.min()) / (Z.max() - Z.min())



array([[0.90302823, 0.85568811, 0.36020185, 0.        , 0.71472349],
       [0.64258084, 0.16088883, 0.33424872, 0.64465386, 0.75255061],
       [1.        , 0.37847586, 0.68288125, 0.99818994, 0.82398737],
       [0.49219342, 0.21223222, 0.1258225 , 0.45819678, 0.36938383],
       [0.67056392, 0.93927616, 0.61215275, 0.37203004, 0.44583886]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))

print('A = ',A, sep='\n')
print('B = ',B, sep='\n')

np.dot(A, B)

A = 
[[0.82269088 0.20272148 0.71282602]
 [0.27884589 0.57112285 0.41093085]
 [0.02123317 0.42715913 0.72749636]
 [0.73590872 0.07848997 0.17180955]
 [0.68382463 0.12722995 0.5022196 ]]
B = 
[[0.86898645 0.22765329]
 [0.2881567  0.56727   ]
 [0.27007377 0.86903774]]


array([[0.96583839, 0.92175881],
       [0.51786782, 0.74457546],
       [0.33801779, 0.87937015],
       [0.70851337, 0.36136603],
       [0.76653284, 0.66429645]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [69]:
a = np.array([1,2,3,4,5,6,7,8,9])
mask = (a>3) & (a<8)
a[mask] = -a[mask]
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [74]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

legal
legal
illegal
legal
legal
illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([-9.22337204e+18])


#### 29. How to round away from zero a float array ? (★☆☆)

In [12]:
a = np.array([1.2, -1.2, 2.0, -2.0, 0.3, -0.3])
np.sign(a)*np.ceil(np.abs(a))

array([ 2., -2.,  2., -2.,  1., -1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [13]:
ar1 = np.array([12, 14, 15, 16, 17])
ar2 = [2, 4, 5, 6, 7, 8, 9, 12]
np.intersect1d(ar1, ar2)


array([12])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [14]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [17]:
from datetime import date, timedelta

today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2025-12-28
Today: 2025-12-29
Tomorrow: 2025-12-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
from datetime import date, timedelta

start = date(2016, 7, 1)
end = date(2016, 8, 1)
dates = []
current = start

while current < end:
    dates.append(current)
    current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [48]:
a = np.random.rand(5)*10
np.floor(a)
np.astype(a,int)
np.trunc(a).astype(int)
(a//1).astype(int)

array([2, 6, 2, 5, 6])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [30]:
np.tile(np.arange(0,5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [65]:
import random
def generate():
  arr =[]
  for i in range(0, 11):
    arr.append(random.random())
  return arr
generate()

[0.7216215034642667,
 0.5760163235888366,
 0.17036211545818924,
 0.9582041728001932,
 0.30923775633941375,
 0.19052560664416862,
 0.16128812884670585,
 0.01250789578373579,
 0.00987795023238025,
 0.9050267765697657,
 0.15344236349018958]

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [72]:
np.random.rand(10)

array([0.85827161, 0.85226522, 0.45515279, 0.52637972, 0.99044724,
       0.51393032, 0.89864557, 0.09299671, 0.44760216, 0.87019146])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [78]:
a = np.random.random(10)
np.sort(a)

array([0.01263061, 0.02438444, 0.03751563, 0.09086942, 0.18261176,
       0.28181756, 0.6235462 , 0.71935361, 0.86961011, 0.98222725])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [79]:
a = np.array([1, 2, 3, 4, 5])

sum(a)
np.sum(a)

np.int64(15)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [83]:
A = np.random.random(5)
B = np.random.random(5)
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [88]:
A = np.array([1, 2, 3, 4, 5])
A.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)